dist: bionic
language: node_js
node_js:
 - "node"
os:
  - linux
  - osx
  - windows

#before_install:
#  - npm i -g npm@latest

script:

  - npx scryptlib download
  - npm test -- --ci=true